#!/usr/bin/env node

/**
 * Batched deploy for large asset sets.
 * Splits site files into batches under a size limit, deploying each with inherit:true
 * so previous batch files are preserved.
 *
 * Usage: RUN402_PROJECT_ID=prj_xxx SUBDOMAIN=eagles node deploy-batched.js
 */

import { execSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = new URL('.', import.meta.url).pathname;
const MAX_BATCH_BYTES = 25 * 1024 * 1024; // 25MB per batch (before base64 expansion)

function readText(path) {
  return readFileSync(join(ROOT, path), 'utf-8');
}

function collectFilesWithSize(dir, base = dir) {
  const files = [];
  if (!existsSync(join(ROOT, dir))) return files;
  for (const entry of readdirSync(join(ROOT, dir), { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectFilesWithSize(full, base));
    } else {
      const size = statSync(join(ROOT, full)).size;
      files.push({ file: relative(base, full), path: `./${full}`, size });
    }
  }
  return files;
}

function collectFunctions(dir) {
  if (!existsSync(join(ROOT, dir))) return [];
  return readdirSync(join(ROOT, dir))
    .filter((f) => f.endsWith('.js'))
    .map((f) => {
      const name = f.replace('.js', '');
      const code = readText(join(dir, f));
      const scheduleMatch = code.match(/\/\/\s*schedule:\s*"([^"]+)"/);
      const fn = { name, code };
      if (scheduleMatch) fn.schedule = scheduleMatch[1];
      return fn;
    });
}

// Resolve project ID
const projectId =
  process.env.RUN402_PROJECT_ID ||
  (() => {
    try {
      const out = execSync('run402 projects list', { encoding: 'utf-8' });
      const projects = JSON.parse(out);
      const active = projects.find((p) => p.active);
      if (active) return active.project_id;
      if (projects.length > 0) return projects[0].project_id;
    } catch {}
    console.error('No RUN402_PROJECT_ID set and no active run402 project found.');
    process.exit(1);
  })();

const subdomain = process.env.SUBDOMAIN || 'kychon';

// Resolve anon_key
let anonKey = process.env.ANON_KEY || '';
if (!anonKey) {
  try {
    const keysOut = execSync(`run402 projects keys ${projectId}`, { encoding: 'utf-8' });
    const keys = JSON.parse(keysOut);
    anonKey = keys.anon_key || '';
  } catch {}
}
if (!anonKey) {
  console.error('Could not resolve anon_key.');
  process.exit(1);
}

// Build Astro project
console.log('Building Astro project...');
execSync('npx astro build', { encoding: 'utf-8', stdio: 'inherit' });

// Inject anon_key into dist/js/env.js (post-build)
const envJsPath = join(ROOT, 'dist', 'js', 'env.js');
const envJsContent = `// env.js — Runtime config (auto-generated by deploy.js)\nwindow.__KYCHON_API = 'https://api.run402.com';\nwindow.__KYCHON_ANON_KEY = '${anonKey}';\n`;
writeFileSync(envJsPath, envJsContent);

// Collect all site files with sizes from Astro build output
const allFiles = collectFilesWithSize('dist', 'dist');

// Separate: large binary files (images) vs small code files
const imageFiles = allFiles.filter(f => /\.(jpg|jpeg|png|gif|webp|svg|ico)$/i.test(f.file));
const codeFiles = allFiles.filter(f => !/\.(jpg|jpeg|png|gif|webp|svg|ico)$/i.test(f.file));

// Split images into batches
const imageBatches = [];
let currentBatch = [];
let currentSize = 0;
for (const f of imageFiles) {
  if (currentSize + f.size > MAX_BATCH_BYTES && currentBatch.length > 0) {
    imageBatches.push(currentBatch);
    currentBatch = [];
    currentSize = 0;
  }
  currentBatch.push(f);
  currentSize += f.size;
}
if (currentBatch.length > 0) imageBatches.push(currentBatch);

// Collect functions (respect EXCLUDE_FUNCTIONS + EXTRA_FUNCTION env vars)
let functions = collectFunctions('functions');
if (process.env.EXCLUDE_FUNCTIONS) {
  const exclude = new Set(process.env.EXCLUDE_FUNCTIONS.split(',').map((s) => s.trim()));
  functions = functions.filter((f) => !exclude.has(f.name));
}
if (process.env.EXTRA_FUNCTION) {
  const extraPath = process.env.EXTRA_FUNCTION;
  const name = extraPath.split('/').pop().replace('.js', '');
  const code = readText(extraPath);
  const scheduleMatch = code.match(/\/\/\s*schedule:\s*"([^"]+)"/);
  const fn = { name, code };
  if (scheduleMatch) fn.schedule = scheduleMatch[1];
  functions.push(fn);
}

// RLS
const rls = {
  template: 'public_read',
  tables: [
    { table: 'site_config' }, { table: 'pages' }, { table: 'sections' },
    { table: 'membership_tiers' }, { table: 'member_custom_fields' },
    { table: 'announcements' }, { table: 'activity_log' }, { table: 'members' },
    { table: 'events' }, { table: 'event_rsvps' }, { table: 'resources' },
    { table: 'forum_categories' }, { table: 'forum_topics' }, { table: 'forum_replies' },
    { table: 'committees' }, { table: 'committee_members' },
    { table: 'content_translations' }, { table: 'moderation_log' },
    { table: 'member_insights' }, { table: 'newsletter_drafts' }, { table: 'reactions' },
  ],
};

// Migrations
const schema = readText('schema.sql');
const seed = readText(process.env.SEED_FILE || 'seed.sql');
const migrations = `${schema}\n\n${seed}`;
const migrationsPath = join(ROOT, '.migrations.sql');
writeFileSync(migrationsPath, migrations);

const totalBatches = imageBatches.length + 1; // +1 for code batch
console.log(`Deploying to ${projectId} (subdomain: ${subdomain})`);
console.log(`  ${imageFiles.length} images in ${imageBatches.length} batch(es)`);
console.log(`  ${codeFiles.length} code files + ${functions.length} functions in final batch`);

function deploy(manifest, label) {
  const manifestPath = join(ROOT, `app-batch.json`);
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
  console.log(`\n--- ${label} (${manifest.files.length} files) ---`);
  try {
    const result = execSync(`run402 deploy --manifest "${manifestPath}"`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    const parsed = JSON.parse(result);
    console.log(`  OK`);
    return parsed;
  } catch (err) {
    console.error(`  FAILED:`, err.stderr || err.message);
    process.exit(1);
  }
}

// Deploy image batches (no migrations/functions/rls — just files + inherit)
for (let i = 0; i < imageBatches.length; i++) {
  const batch = imageBatches[i];
  const batchSize = batch.reduce((s, f) => s + f.size, 0);
  const files = batch.map(({ file, path }) => ({ file, path }));
  deploy(
    { project_id: projectId, files, subdomain, inherit: i > 0 },
    `Batch ${i + 1}/${totalBatches}: ${files.length} images (~${(batchSize / 1024 / 1024).toFixed(1)}MB)`
  );
}

// Deploy code files + migrations + functions + rls (final batch, inherit from images)
const codeFilesClean = codeFiles.map(({ file, path }) => ({ file, path }));
const finalManifest = {
  project_id: projectId,
  migrations_file: '.migrations.sql',
  rls,
  files: codeFilesClean,
  subdomain,
  inherit: true,
};
if (functions.length > 0) finalManifest.functions = functions;

const result = deploy(finalManifest, `Batch ${totalBatches}/${totalBatches}: code + migrations + functions`);
console.log('\nDeploy complete!');
if (result.subdomain_url) console.log('Live at:', result.subdomain_url);
