import type { ProjectSeed } from './types.js';

const DEFAULT_NAV_ITEMS = [
  { label: 'Home', href: '/', icon: 'home', public: true },
  { label: 'Members', href: '/directory', icon: 'users', auth: true, feature: 'feature_directory' },
  { label: 'Events', href: '/events', icon: 'calendar', feature: 'feature_events' },
  { label: 'Resources', href: '/resources', icon: 'book-open', feature: 'feature_resources' },
  { label: 'Forum', href: '/forum', icon: 'message-circle', feature: 'feature_forum' },
  { label: 'Committees', href: '/committees', icon: 'briefcase', feature: 'feature_committees' },
  { label: 'Polls', href: '/polls', icon: 'bar-chart', feature: 'feature_polls' },
  { label: 'Dashboard', href: '/admin', icon: 'bar-chart-2', admin: true },
  { label: 'Members', href: '/admin-members', icon: 'users', admin: true },
  { label: 'Settings', href: '/admin-settings', icon: 'settings', admin: true },
];

export const seed: ProjectSeed = {
  site_config: {
    site_name: { value: 'Kychon Community', category: 'branding' },
    site_tagline: { value: 'Your AI-powered community platform', category: 'branding' },
    site_description: { value: 'A modern membership portal — own your data, customize with AI.', category: 'branding' },
    // Brand identity — picker rules: icon → wordmark → text. Template default
    // is text-only (safe baseline; admins add an icon or wordmark in settings).
    brand_text: { value: 'Kychon Community', category: 'branding' },
    brand_text_short: { value: 'Kychon', category: 'branding' },
    brand_icon_url: { value: '', category: 'branding' },
    brand_wordmark_url: { value: '', category: 'branding' },
    favicon_url: { value: '', category: 'branding' },
    theme: {
      value: {
        primary: '#6366f1',
        primary_hover: '#4f46e5',
        bg: '#ffffff',
        surface: '#f8fafc',
        text: '#0f172a',
        text_muted: '#64748b',
        border: '#e2e8f0',
        font_heading: 'Inter',
        font_body: 'Inter',
        radius: '0.5rem',
        max_width: '72rem',
      },
      category: 'theme',
    },
    feature_events: { value: true, category: 'features' },
    feature_forum: { value: false, category: 'features' },
    feature_directory: { value: true, category: 'features' },
    feature_resources: { value: true, category: 'features' },
    feature_blog: { value: false, category: 'features' },
    feature_committees: { value: false, category: 'features' },
    feature_ai_moderation: { value: false, category: 'features' },
    feature_ai_translation: { value: false, category: 'features' },
    feature_ai_newsletter: { value: false, category: 'features' },
    feature_ai_insights: { value: false, category: 'features' },
    feature_ai_onboarding: { value: false, category: 'features' },
    feature_ai_event_recaps: { value: false, category: 'features' },
    directory_public: { value: false, category: 'features' },
    signup_mode: { value: 'approved', category: 'features' },
    feature_activity_feed: { value: true, category: 'features' },
    feature_reactions: { value: true, category: 'features' },
    feature_polls: { value: true, category: 'features' },
    polls_member_create: { value: false, category: 'features' },
    event_time_display_mode: { value: 'visitor', category: 'events' },
  },
  membership_tiers: [
    {
      name: 'Member',
      description: 'Standard membership',
      benefits: ['Member directory', 'Announcements', 'Events'],
      price_label: 'Free',
      position: 1,
      is_default: true,
    },
    {
      name: 'Premium',
      description: 'Premium membership with full access',
      benefits: ['Member directory', 'Announcements', 'Events', 'Resources', 'Forum'],
      price_label: '$50/year',
      position: 2,
      is_default: false,
    },
  ],
  sections: [
    // --- Header chrome (global) ---
    {
      page_slug: '*',
      zone: 'header',
      scope: 'global',
      section_type: 'brand_header',
      // brand_header reads site_config keys via the picker rules — block-level
      // overrides on the section row aren't used.
      config: { href: '/' },
      position: 1,
    },
    {
      page_slug: '*',
      zone: 'header',
      scope: 'global',
      section_type: 'nav',
      config: { items: DEFAULT_NAV_ITEMS },
      position: 2,
    },
    {
      page_slug: '*',
      zone: 'header',
      scope: 'global',
      section_type: 'sign_in_bar',
      config: { show_lang_toggle: true, show_theme_toggle: true },
      position: 3,
    },
    // --- Homepage main ---
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'hero',
      config: {
        heading: 'Welcome to Our Community',
        subheading: 'Connect, collaborate, and grow together.',
        cta_text: 'Join Now',
        cta_href: '#signup',
      },
      position: 1,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'features',
      config: {
        columns: 3,
        items: [
          { icon: 'users', title: 'Member Directory', desc: 'Connect with fellow members and grow your network.' },
          { icon: 'calendar', title: 'Events', desc: 'Stay updated on upcoming meetups, workshops, and socials.' },
          { icon: 'book-open', title: 'Resources', desc: 'Access exclusive guides, templates, and recordings.' },
        ],
      },
      position: 2,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'cta',
      config: {
        heading: 'Ready to join?',
        text: 'Sign up today and become part of our community.',
        cta_text: 'Get Started',
        cta_href: '#signup',
      },
      position: 3,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'announcements_feed',
      config: { heading: 'Announcements', limit: 20 },
      position: 4,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'activity_feed',
      config: { heading: 'Recent Activity', limit: 15 },
      position: 5,
    },
    // --- Footer chrome (global) ---
    {
      page_slug: '*',
      zone: 'footer',
      scope: 'global',
      section_type: 'footer_attribution',
      config: { text: 'Powered by [Kychon](https://kychon.com) on [Run402](https://run402.com)' },
      position: 99,
    },
  ],
};
