#!/bin/bash
# Deploy Silver Pines demo to Run402
# Usage: bash demo/silver-pines/deploy.sh
set -e

PROJECT_ID="REDACTED_PROJECT_ID"
SUBDOMAIN="silver-pines"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

echo "=== Silver Pines Demo Deploy ==="

# 1. Get anon_key
echo "Getting project keys..."
ANON_KEY=$(run402 projects keys "$PROJECT_ID" | jq -r '.anon_key')
echo "  anon_key: ${ANON_KEY:0:20}..."

# 2. Write env.js with the correct anon_key
cat > "$ROOT/site/js/env.js" <<ENVEOF
// env.js — Runtime config (auto-generated by deploy)
window.__WILDLYCHEE_API = 'https://api.run402.com';
window.__WILDLYCHEE_ANON_KEY = '${ANON_KEY}';
ENVEOF

# 3. Combine schema + silver pines seed
echo "Preparing migrations (schema + silver-pines seed)..."
cat "$ROOT/schema.sql" "$ROOT/demo/silver-pines/seed.sql" > "$ROOT/.migrations-silver-pines.sql"

# 4. Resize images to web-friendly sizes in a temp directory (keep originals untouched)
echo "Preparing web-sized images..."
WEB_ASSETS=$(mktemp -d)
trap "rm -rf $WEB_ASSETS" EXIT
for f in "$ROOT/demo/silver-pines/assets"/avatar-*.jpg; do
  sips -Z 400 "$f" --out "$WEB_ASSETS/$(basename "$f")" >/dev/null 2>&1
done
for f in "$ROOT/demo/silver-pines/assets"/event-*.jpg "$ROOT/demo/silver-pines/assets"/hero.jpg; do
  [ -f "$f" ] && sips -Z 1200 "$f" --out "$WEB_ASSETS/$(basename "$f")" >/dev/null 2>&1
done
for f in "$ROOT/demo/silver-pines/assets"/logo.png; do
  [ -f "$f" ] && sips -Z 400 "$f" --out "$WEB_ASSETS/$(basename "$f")" >/dev/null 2>&1
done
echo "  $(ls "$WEB_ASSETS" | wc -l | tr -d ' ') images ($(du -sh "$WEB_ASSETS" | cut -f1) web-optimized)"
export WEB_ASSETS

# 5. Build manifest — site files + web-sized demo assets mapped as assets/*
echo "Building manifest..."
node --input-type=module <<SCRIPT
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = '${ROOT}';

function collectFiles(dir, base = dir) {
  const files = [];
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return files;
  for (const entry of readdirSync(abs, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...collectFiles(full, base));
    else files.push({ file: relative(base, full), path: './' + full });
  }
  return files;
}

function collectFunctions(dir) {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return [];
  return readdirSync(abs).filter(f => f.endsWith('.js')).map(f => {
    const name = f.replace('.js', '');
    const code = readFileSync(join(abs, f), 'utf-8');
    const m = code.match(/\\/\\/\\s*schedule:\\s*"([^"]+)"/);
    const fn = { name, code };
    if (m) fn.schedule = m[1];
    return fn;
  });
}

// Site files (template)
const siteFiles = collectFiles('site', 'site');

// Demo assets — web-optimized images from temp dir, mapped as assets/*
const webAssets = process.env.WEB_ASSETS;
if (webAssets && existsSync(webAssets)) {
  for (const f of readdirSync(webAssets)) {
    siteFiles.push({ file: 'assets/' + f, path: join(webAssets, f) });
  }
}

const functions = collectFunctions('functions');

const rls = {
  template: 'public_read',
  tables: [
    { table: 'site_config' }, { table: 'pages' }, { table: 'sections' },
    { table: 'membership_tiers' }, { table: 'member_custom_fields' },
    { table: 'announcements' }, { table: 'activity_log' },
    { table: 'members' }, { table: 'events' }, { table: 'event_rsvps' },
    { table: 'resources' }, { table: 'forum_categories' },
    { table: 'forum_topics' }, { table: 'forum_replies' },
    { table: 'committees' }, { table: 'committee_members' },
    { table: 'content_translations' }, { table: 'moderation_log' },
    { table: 'member_insights' }, { table: 'newsletter_drafts' },
    { table: 'reactions' },
  ],
};

const manifest = {
  project_id: '${PROJECT_ID}',
  migrations_file: '.migrations-silver-pines.sql',
  rls,
  files: siteFiles,
  subdomain: '${SUBDOMAIN}',
};
if (functions.length > 0) manifest.functions = functions;

const path = join(ROOT, 'app-silver-pines.json');
writeFileSync(path, JSON.stringify(manifest, null, 2));
console.log('  ' + siteFiles.length + ' site files (' + siteFiles.filter(f => f.file.startsWith('assets/')).length + ' demo assets), ' + functions.length + ' functions');
SCRIPT

# 5. Deploy with explicit project ID
echo "Deploying to $PROJECT_ID..."
run402 deploy --manifest "$ROOT/app-silver-pines.json" --project "$PROJECT_ID" 2>&1 | tee /dev/stderr | jq -r '.deployment_id // empty'

echo ""
echo "=== Done! ==="
echo "Live at: https://${SUBDOMAIN}.run402.com"
