#!/bin/bash
# Deploy Silver Pines demo to Run402
# Usage: bash demo/silver-pines/deploy.sh
set -e

PROJECT_ID="REDACTED_PROJECT_ID"
SUBDOMAIN="silver-pines"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

echo "=== Silver Pines Demo Deploy ==="

# 1. Get anon_key
echo "Getting project keys..."
ANON_KEY=$(run402 projects keys "$PROJECT_ID" | jq -r '.anon_key')
echo "  anon_key: ${ANON_KEY:0:20}..."

# 2. Write env.js with the correct anon_key
cat > "$ROOT/site/js/env.js" <<ENVEOF
// env.js — Runtime config (auto-generated by deploy)
window.__WILDLYCHEE_API = 'https://api.run402.com';
window.__WILDLYCHEE_ANON_KEY = '${ANON_KEY}';
ENVEOF

# 3. Combine schema + silver pines seed into migrations file
echo "Preparing migrations (schema + silver-pines seed)..."
cat "$ROOT/schema.sql" "$ROOT/demo/silver-pines/seed.sql" > "$ROOT/.migrations-silver-pines.sql"

# 4. Upload images to storage
echo "Uploading images to storage..."
ASSETS_DIR="$ROOT/demo/silver-pines/assets"
for img in "$ASSETS_DIR"/*; do
  fname=$(basename "$img")
  echo "  upload: assets/$fname"
  run402 storage upload "$PROJECT_ID" public "assets/$fname" --file "$img" 2>/dev/null || true
done

# 5. Generate manifest using node (reuse file-collection logic)
echo "Building manifest..."
node --input-type=module <<'SCRIPT'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = process.env.ROOT;
const projectId = process.env.PROJECT_ID;
const subdomain = process.env.SUBDOMAIN;

function collectFiles(dir, base = dir) {
  const files = [];
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return files;
  for (const entry of readdirSync(abs, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectFiles(full, base));
    } else {
      files.push({ file: relative(base, full), path: './' + full });
    }
  }
  return files;
}

function collectFunctions(dir) {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return [];
  return readdirSync(abs)
    .filter(f => f.endsWith('.js'))
    .map(f => {
      const name = f.replace('.js', '');
      const code = readFileSync(join(abs, f), 'utf-8');
      const scheduleMatch = code.match(/\/\/\s*schedule:\s*"([^"]+)"/);
      const fn = { name, code };
      if (scheduleMatch) fn.schedule = scheduleMatch[1];
      return fn;
    });
}

const siteFiles = collectFiles('site', 'site');
const functions = collectFunctions('functions');

const rls = {
  template: 'public_read',
  tables: [
    { table: 'site_config' }, { table: 'pages' }, { table: 'sections' },
    { table: 'membership_tiers' }, { table: 'member_custom_fields' },
    { table: 'announcements' }, { table: 'activity_log' },
    { table: 'members' }, { table: 'events' }, { table: 'event_rsvps' },
    { table: 'resources' }, { table: 'forum_categories' },
    { table: 'forum_topics' }, { table: 'forum_replies' },
    { table: 'committees' }, { table: 'committee_members' },
    { table: 'content_translations' }, { table: 'moderation_log' },
    { table: 'member_insights' }, { table: 'newsletter_drafts' },
    { table: 'reactions' },
  ],
};

const manifest = {
  project_id: projectId,
  migrations_file: '.migrations-silver-pines.sql',
  rls,
  files: siteFiles,
  subdomain,
};
if (functions.length > 0) manifest.functions = functions;

const path = join(ROOT, 'app-silver-pines.json');
writeFileSync(path, JSON.stringify(manifest, null, 2));
console.log(`  ${siteFiles.length} site files, ${functions.length} functions`);
SCRIPT

# 6. Deploy
echo "Deploying..."
RESULT=$(run402 deploy --manifest "$ROOT/app-silver-pines.json" 2>&1)
echo "$RESULT" | jq '.' 2>/dev/null || echo "$RESULT"

echo ""
echo "=== Done! ==="
echo "Live at: https://${SUBDOMAIN}.run402.com"
