/**
 * Shared utilities for scripts/deploy.ts.
 *
 * All Run402 interactions go through `@run402/sdk/node` — no execSync calls.
 * Per the deploy spec policy, new tooling targeting Run402 must use the SDK.
 */

import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";

import { fileSetFromDir, run402 } from "@run402/sdk/node";
import type { FileSet, FunctionSpec, ReleaseSpec } from "@run402/sdk/node";

type Run402Instance = ReturnType<typeof run402>;
export type { FileSet, FunctionSpec, ReleaseSpec };
export { fileSetFromDir };

/**
 * Tables reachable via `/rest/v1/*`. Sent as `database.expose.tables: string[]`
 * in the v2 release spec.
 *
 * Note: the SDK's `ExposeManifest.tables` type is `Array<Record<string, unknown>>`
 * (matching the published schema at https://run402.com/schemas/manifest.v1.json,
 * which describes objects with `{name, expose, policy}`), but the gateway
 * runtime validator rejects that shape with `"tables must be an array of strings"`.
 * Strings is what works today — see the friction note in `docs/run402-feedback.md`.
 */
export const EXPOSE_TABLES: readonly string[] = [
  "site_config",
  "pages",
  "sections",
  "membership_tiers",
  "member_custom_fields",
  "announcements",
  "activity_log",
  "members",
  "events",
  "event_rsvps",
  "resources",
  "forum_categories",
  "forum_topics",
  "forum_replies",
  "committees",
  "committee_members",
  "content_translations",
  "moderation_log",
  "member_insights",
  "newsletter_drafts",
  "reactions",
];

/**
 * Read functions from a directory of `.js` files. Each file becomes one
 * `FunctionSpec` in the `replace` map; cron schedules are parsed from
 * `// schedule: "..."` comments.
 *
 * Honors two env-var overrides used by the demo deploys:
 *   - `EXCLUDE_FUNCTIONS=name1,name2` — skip these names
 *   - `EXTRA_FUNCTION=path/to/file.js` — append this single file as an extra function
 */
export async function collectFunctionsMap(
  dir: string,
): Promise<Record<string, FunctionSpec>> {
  const out: Record<string, FunctionSpec> = {};
  if (existsSync(dir)) {
    const entries = await readdir(dir);
    for (const f of entries.filter((e) => e.endsWith(".js"))) {
      const code = await readFile(join(dir, f), "utf-8");
      out[f.replace(/\.js$/, "")] = makeFunctionSpec(code);
    }
  }

  const exclude = process.env["EXCLUDE_FUNCTIONS"];
  if (exclude) {
    for (const name of exclude.split(",").map((s) => s.trim())) {
      delete out[name];
    }
  }

  const extra = process.env["EXTRA_FUNCTION"];
  if (extra) {
    const code = await readFile(extra, "utf-8");
    const name = (extra.split("/").pop() ?? extra).replace(/\.js$/, "");
    out[name] = makeFunctionSpec(code);
  }

  return out;
}

function makeFunctionSpec(code: string): FunctionSpec {
  const spec: FunctionSpec = { runtime: "node22", source: code };
  const scheduleMatch = code.match(/\/\/\s*schedule:\s*"([^"]+)"/);
  if (scheduleMatch && scheduleMatch[1]) {
    spec.schedule = scheduleMatch[1];
  }
  return spec;
}

/** Run `npx astro build` from the repo root, streaming output. */
export function buildAstro(): void {
  console.log("Building Astro project...");
  execSync("npx astro build", { stdio: "inherit" });
}

/**
 * Inject the Run402 anon_key into `dist/js/env.js` after `astro build`.
 * Mirrors the runtime config the public site reads at boot. Creates `dist/js/`
 * if Astro hasn't already (no `public/js/` source means the dir is missing).
 */
export function injectEnvJs(distDir: string, anonKey: string): void {
  const jsDir = join(distDir, "js");
  mkdirSync(jsDir, { recursive: true });
  const content =
    "// env.js — Runtime config (auto-generated by deploy)\n" +
    "window.__KYCHON_API = 'https://api.run402.com';\n" +
    `window.__KYCHON_ANON_KEY = '${anonKey}';\n`;
  writeFileSync(join(jsDir, "env.js"), content);
}

export interface ResolvedDeployTarget {
  projectId: string;
  anonKey: string;
  subdomain: string;
}

/**
 * Resolve the project id (env var → SDK active project), then fetch the
 * anon_key from the local keystore. Errors out with an actionable message
 * if either step fails.
 */
export async function resolveDeployTarget(r: Run402Instance): Promise<ResolvedDeployTarget> {
  const fromEnv = process.env["RUN402_PROJECT_ID"];
  let projectId: string;
  if (fromEnv && fromEnv.length > 0) {
    projectId = fromEnv;
  } else {
    const active = await r.projects.active();
    if (!active) {
      throw new Error(
        "No project id resolved.\n" +
          "  Set RUN402_PROJECT_ID, or run `run402 projects use <id>` to set the active project.",
      );
    }
    projectId = active;
  }

  const fromEnvAnon = process.env["ANON_KEY"];
  let anonKey: string;
  if (fromEnvAnon && fromEnvAnon.length > 0) {
    anonKey = fromEnvAnon;
  } else {
    const keys = await r.projects.keys(projectId);
    anonKey = keys.anon_key;
  }
  if (!anonKey) {
    throw new Error(
      `Could not resolve anon_key for project ${projectId}.\n` +
        "  Set ANON_KEY, or ensure the project exists in the local keystore.",
    );
  }

  const subdomain = process.env["SUBDOMAIN"] ?? "kychon";
  return { projectId, anonKey, subdomain };
}

/** Read schema.sql + seed.sql (or override) and concatenate. Returns inline migrations. */
export function readMigrations(root: string): string {
  const schemaPath = join(root, "schema.sql");
  const seedPath = join(root, process.env["SEED_FILE"] ?? "seed.sql");
  const schema = readFileSync(schemaPath, "utf-8");
  const seed = existsSync(seedPath) ? readFileSync(seedPath, "utf-8") : "";
  return `${schema}\n\n${seed}`;
}

/** Lowercase hex SHA-256 of a string. Used to derive stable migration ids. */
export function sha256Hex(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

/**
 * Format an SDK error for human-readable console output. Distinguishes
 * Run402DeployError / PaymentRequired / Unauthorized / ApiError /
 * NetworkError / LocalError so the next-action message points at the
 * right fix.
 */
export async function prettyPrintError(err: unknown): Promise<string> {
  const sdk = await import("@run402/sdk");
  if (err instanceof sdk.Run402DeployError) {
    const fixHint = err.fix
      ? `\n  Suggested fix: ${err.fix.action}${err.fix.path ? ` @ ${err.fix.path}` : ""}`
      : "";
    return (
      `Deploy error [${err.code}] in phase "${err.phase}" (resource: ${err.resource}): ${err.message}${fixHint}`
    );
  }
  if (err instanceof sdk.PaymentRequired) {
    return (
      `Payment required (HTTP ${err.status ?? "?"}) while ${err.context}: ${err.message}\n` +
      "  Fix: run `run402 tier set <name>` to renew (prototype $0.10 / hobby $5 / team $20),\n" +
      "       or run `run402 billing` to top up the allowance balance first."
    );
  }
  if (err instanceof sdk.Unauthorized) {
    return (
      `Unauthorized (HTTP ${err.status ?? "?"}) while ${err.context}: ${err.message}\n` +
      "  Fix: ensure the project is in your keystore and the allowance is configured."
    );
  }
  if (err instanceof sdk.ApiError) {
    const bodyStr = err.body ? `\n  Server body: ${JSON.stringify(err.body)}` : "";
    return `API error (HTTP ${err.status ?? "?"}) while ${err.context}: ${err.message}${bodyStr}`;
  }
  if (err instanceof sdk.NetworkError) {
    return `Network error while ${err.context}: ${err.message}`;
  }
  if (err instanceof sdk.LocalError) {
    return (
      `Local error while ${err.context}: ${err.message}\n` +
      "  No HTTP request was made. Likely an input/filesystem issue (missing file, unreadable dir)."
    );
  }
  if (err instanceof sdk.Run402Error) {
    const httpHint = err.status ? ` (HTTP ${err.status})` : "";
    return `Run402 error${httpHint} while ${err.context}: ${err.message}`;
  }
  if (err instanceof Error) return `Unexpected error: ${err.message}`;
  return `Unexpected non-error throw: ${String(err)}`;
}

/** Tiny argv check for the --dry-run flag. */
export function isDryRun(argv: readonly string[]): boolean {
  return argv.includes("--dry-run");
}

/** Format a byte count as a short human-readable string ("1.4MB", "812KB", "402B"). */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)}MB`;
}
