/**
 * Shared utilities for the deploy scripts.
 *
 * All Run402 interactions go through `@run402/sdk/node` — no execSync calls.
 * Per the deploy spec policy, new tooling targeting Run402 must use the SDK.
 */

import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { fileSetFromDir, run402 } from "@run402/sdk/node";
import type { FileSet, FunctionSpec, ReleaseSpec } from "@run402/sdk/node";

type Run402Instance = ReturnType<typeof run402>;
export type { FileSet, FunctionSpec, ReleaseSpec, Run402Instance };
export { fileSetFromDir };

/** Repo root, derived from this file's location. */
export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Tables reachable via `/rest/v1/*`, sent as `database.expose.tables` in the
 * v2 release spec. Rich-object shape per the published manifest schema at
 * https://run402.com/schemas/manifest.v1.json.
 *
 * The previous workaround (sending bare strings + structural cast) is no
 * longer needed: the gateway's v2 validator was relaxed to delegate to the
 * same `validateManifest()` the imperative `/expose` route uses (kychee-com/run402#154).
 * Setting `policy` explicitly here also pins the RLS template — strings
 * implicitly default to `public_read_authenticated_write` server-side, which
 * is what we want, but explicit beats implicit.
 */
const TABLE_NAMES = [
  "site_config",
  "pages",
  "sections",
  "membership_tiers",
  "member_custom_fields",
  "announcements",
  "activity_log",
  "members",
  "events",
  "event_rsvps",
  "resources",
  "forum_categories",
  "forum_topics",
  "forum_replies",
  "committees",
  "committee_members",
  "content_translations",
  "moderation_log",
  "member_insights",
  "newsletter_drafts",
  "reactions",
] as const;

export const EXPOSE_TABLES: ReadonlyArray<Record<string, unknown>> = TABLE_NAMES.map(
  (name) => ({ name, expose: true, policy: "public_read_authenticated_write" }),
);

export interface CollectFunctionsOptions {
  /** Function names to skip (e.g. `["check-expirations"]` for demos). */
  exclude?: readonly string[];
  /** Path to an additional `.js` function to append (e.g. demo reset-demo). */
  extraFunction?: string;
}

/**
 * Read functions from a directory of `.js` files. Each file becomes one
 * `FunctionSpec` in the `replace` map; cron schedules are parsed from
 * `// schedule: "..."` comments.
 */
export async function collectFunctionsMap(
  dir: string,
  opts: CollectFunctionsOptions = {},
): Promise<Record<string, FunctionSpec>> {
  const out: Record<string, FunctionSpec> = {};
  if (existsSync(dir)) {
    const entries = await readdir(dir);
    for (const f of entries.filter((e) => e.endsWith(".js"))) {
      const code = await readFile(join(dir, f), "utf-8");
      out[f.replace(/\.js$/, "")] = makeFunctionSpec(code);
    }
  }

  if (opts.exclude) {
    for (const name of opts.exclude) delete out[name];
  }

  if (opts.extraFunction) {
    const code = await readFile(opts.extraFunction, "utf-8");
    const name = (opts.extraFunction.split("/").pop() ?? opts.extraFunction).replace(/\.js$/, "");
    out[name] = makeFunctionSpec(code);
  }

  return out;
}

function makeFunctionSpec(code: string): FunctionSpec {
  const spec: FunctionSpec = { runtime: "node22", source: code };
  const scheduleMatch = code.match(/\/\/\s*schedule:\s*"([^"]+)"/);
  if (scheduleMatch && scheduleMatch[1]) {
    spec.schedule = scheduleMatch[1];
  }
  return spec;
}

/** Run `npx astro build` from the repo root, streaming output. */
export function buildAstro(): void {
  console.log("Building Astro project...");
  execSync("npx astro build", { stdio: "inherit", cwd: ROOT });
}

/**
 * Inject the Run402 anon_key into `dist/js/env.js` after `astro build`.
 * Mirrors the runtime config the public site reads at boot.
 */
export function injectEnvJs(distDir: string, anonKey: string): void {
  const jsDir = join(distDir, "js");
  mkdirSync(jsDir, { recursive: true });
  const content =
    "// env.js — Runtime config (auto-generated by deploy)\n" +
    "window.__KYCHON_API = 'https://api.run402.com';\n" +
    `window.__KYCHON_ANON_KEY = '${anonKey}';\n`;
  writeFileSync(join(jsDir, "env.js"), content);
}

export interface ResolvedDeployTarget {
  projectId: string;
  anonKey: string;
  subdomain: string;
}

/**
 * Resolve target from env vars (RUN402_PROJECT_ID / ANON_KEY / SUBDOMAIN),
 * falling back to the SDK's active project + keystore. Used by `deploy.ts`
 * (production deploy entry point).
 */
export async function resolveDeployTarget(r: Run402Instance): Promise<ResolvedDeployTarget> {
  const fromEnv = process.env["RUN402_PROJECT_ID"];
  let projectId: string;
  if (fromEnv && fromEnv.length > 0) {
    projectId = fromEnv;
  } else {
    const active = await r.projects.active();
    if (!active) {
      throw new Error(
        "No project id resolved.\n" +
          "  Set RUN402_PROJECT_ID, or run `run402 projects use <id>` to set the active project.",
      );
    }
    projectId = active;
  }

  const fromEnvAnon = process.env["ANON_KEY"];
  let anonKey: string;
  if (fromEnvAnon && fromEnvAnon.length > 0) {
    anonKey = fromEnvAnon;
  } else {
    const keys = await r.projects.keys(projectId);
    anonKey = keys.anon_key;
  }
  if (!anonKey) {
    throw new Error(
      `Could not resolve anon_key for project ${projectId}.\n` +
        "  Set ANON_KEY, or ensure the project exists in the local keystore.",
    );
  }

  const subdomain = process.env["SUBDOMAIN"] ?? "kychon";
  return { projectId, anonKey, subdomain };
}

/** Read schema.sql + seed.sql (or override) and concatenate. Returns inline SQL. */
export function readMigrations(root: string, seedFile?: string): string {
  const schemaPath = join(root, "schema.sql");
  const seedPath = join(root, seedFile ?? "seed.sql");
  const schema = readFileSync(schemaPath, "utf-8");
  const seed = existsSync(seedPath) ? readFileSync(seedPath, "utf-8") : "";
  return `${schema}\n\n${seed}`;
}

/** Lowercase hex SHA-256 of a string. Used to derive stable migration ids. */
export function sha256Hex(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

export interface RunDeployOptions {
  projectId: string;
  anonKey: string;
  subdomain: string;
  /** Path to a seed SQL file relative to repo root. Defaults to `seed.sql`. */
  seedFile?: string;
  /** Function names to skip. */
  excludeFunctions?: readonly string[];
  /** Path to an extra function file to add. */
  extraFunction?: string;
  /** When true, prints the assembled spec and returns without calling the API. */
  dryRun?: boolean;
}

export interface RunDeployResult {
  /** True for both real and dry-run successes. */
  ok: true;
  /** Present on real deploys; absent on dry-run. */
  releaseId?: string;
  operationId?: string;
  urls?: Record<string, string>;
  elapsedMs?: number;
}

/**
 * High-level deploy: build Astro, assemble the v2 ReleaseSpec, and call
 * `r.deploy.apply()`. Used by both `deploy.ts` (production) and
 * `deploy-demo.ts` (per-demo orchestration).
 */
export async function runDeploy(
  r: Run402Instance,
  opts: RunDeployOptions,
): Promise<RunDeployResult> {
  buildAstro();

  const distDir = join(ROOT, "dist");
  injectEnvJs(distDir, opts.anonKey);

  const sql = readMigrations(ROOT, opts.seedFile);
  const migrationId = `kychon_${sha256Hex(sql).slice(0, 16)}`;

  const fileSet = await fileSetFromDir(distDir);
  const fileCount = Object.keys(fileSet).length;

  const collectOpts: CollectFunctionsOptions = {};
  if (opts.excludeFunctions) collectOpts.exclude = opts.excludeFunctions;
  if (opts.extraFunction) collectOpts.extraFunction = opts.extraFunction;
  const functionsMap = await collectFunctionsMap(join(ROOT, "functions"), collectOpts);
  const fnNames = Object.keys(functionsMap);
  const scheduledFns = fnNames.filter((n) => functionsMap[n]?.schedule);

  const spec: ReleaseSpec = {
    project: opts.projectId,
    database: {
      migrations: [{ id: migrationId, sql }],
      expose: { version: "1", tables: [...EXPOSE_TABLES] },
    },
    site: { replace: fileSet },
    subdomains: { set: [opts.subdomain] },
  };
  if (fnNames.length > 0) {
    spec.functions = { replace: functionsMap };
  }

  console.log(
    `Deploying to ${opts.projectId} (subdomain: ${opts.subdomain})\n` +
      `  ${fileCount} site files (lazy-streamed from ${distDir})\n` +
      `  ${fnNames.length} functions (${scheduledFns.length} scheduled)\n` +
      `  ${sql.length} migration bytes (id: ${migrationId})`,
  );

  if (opts.dryRun) {
    console.log("\n[dry-run] Would call deploy.apply with:");
    console.log(
      JSON.stringify(
        {
          projectId: opts.projectId,
          subdomain: opts.subdomain,
          filesCount: fileCount,
          functionsCount: fnNames.length,
          functionsWithSchedule: scheduledFns.map(
            (n) => `${n}=${functionsMap[n]?.schedule}`,
          ),
          migrationsBytes: sql.length,
          migrationId,
          exposeTables: EXPOSE_TABLES.length,
        },
        null,
        2,
      ),
    );
    return { ok: true };
  }

  const startedAt = Date.now();
  const result = await r.deploy.apply(spec);
  const elapsedMs = Date.now() - startedAt;

  console.log(`\nDeploy successful in ${(elapsedMs / 1000).toFixed(1)}s`);
  console.log(`  Release id: ${result.release_id}`);
  console.log(`  Operation id: ${result.operation_id}`);
  for (const [k, v] of Object.entries(result.urls)) {
    console.log(`  ${k}: ${v}`);
  }

  return {
    ok: true,
    releaseId: result.release_id,
    operationId: result.operation_id,
    urls: result.urls,
    elapsedMs,
  };
}

/**
 * Format an SDK error for human-readable console output. Distinguishes
 * Run402DeployError / PaymentRequired / Unauthorized / ApiError /
 * NetworkError / LocalError so the next-action message points at the
 * right fix.
 */
export async function prettyPrintError(err: unknown): Promise<string> {
  const sdk = await import("@run402/sdk");
  if (err instanceof sdk.Run402DeployError) {
    const fixHint = err.fix
      ? `\n  Suggested fix: ${err.fix.action}${err.fix.path ? ` @ ${err.fix.path}` : ""}`
      : "";
    return (
      `Deploy error [${err.code}] in phase "${err.phase}" (resource: ${err.resource}): ${err.message}${fixHint}`
    );
  }
  if (err instanceof sdk.PaymentRequired) {
    return (
      `Payment required (HTTP ${err.status ?? "?"}) while ${err.context}: ${err.message}\n` +
      "  Fix: run `run402 tier set <name>` to renew (prototype $0.10 / hobby $5 / team $20),\n" +
      "       or run `run402 billing` to top up the allowance balance first."
    );
  }
  if (err instanceof sdk.Unauthorized) {
    return (
      `Unauthorized (HTTP ${err.status ?? "?"}) while ${err.context}: ${err.message}\n` +
      "  Fix: ensure the project is in your keystore and the allowance is configured."
    );
  }
  if (err instanceof sdk.ApiError) {
    const bodyStr = err.body ? `\n  Server body: ${JSON.stringify(err.body)}` : "";
    return `API error (HTTP ${err.status ?? "?"}) while ${err.context}: ${err.message}${bodyStr}`;
  }
  if (err instanceof sdk.NetworkError) {
    return `Network error while ${err.context}: ${err.message}`;
  }
  if (err instanceof sdk.LocalError) {
    return (
      `Local error while ${err.context}: ${err.message}\n` +
      "  No HTTP request was made. Likely an input/filesystem issue (missing file, unreadable dir)."
    );
  }
  if (err instanceof sdk.Run402Error) {
    const httpHint = err.status ? ` (HTTP ${err.status})` : "";
    return `Run402 error${httpHint} while ${err.context}: ${err.message}`;
  }
  if (err instanceof Error) return `Unexpected error: ${err.message}`;
  return `Unexpected non-error throw: ${String(err)}`;
}

/** Tiny argv check for the --dry-run flag. */
export function isDryRun(argv: readonly string[]): boolean {
  return argv.includes("--dry-run");
}

/** Format a byte count as a short human-readable string ("1.4MB", "812KB", "402B"). */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)}MB`;
}
