import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { type BlockRenderContext, renderBlock, type Section } from '../../src/lib/blocks';

const BLOCKS = resolve(process.cwd(), 'src/lib/blocks.ts');
const BLOCK_HYDRATORS = resolve(process.cwd(), 'src/lib/block-hydrators.ts');
const EMBED = resolve(process.cwd(), 'src/lib/blocks/embed.ts');
const STYLES = resolve(process.cwd(), 'src/styles/public.css');
const ZONE_GRID_STYLES = resolve(process.cwd(), 'src/styles/zone-grid.css');
const EVENT_CALENDAR_RUNTIME = resolve(process.cwd(), 'src/lib/blocks/events-calendar.ts');
const EVENT_CALENDAR_VIEW = resolve(process.cwd(), 'src/components/kychon/EventsCalendarBlockView.tsx');
const SLIDESHOW_RUNTIME = resolve(process.cwd(), 'src/lib/blocks/slideshow.ts');
const NAV_DROPDOWN = resolve(process.cwd(), 'src/lib/nav-dropdown.ts');
const GLOBAL_STYLES = resolve(process.cwd(), 'src/styles/globals.css');
const ADMIN_STYLES = resolve(process.cwd(), 'public/css/admin-editing.css');
const PUBLIC_ZONE_GRID_STYLES = resolve(process.cwd(), 'public/css/zone-grid.css');
const A11Y_STYLES = resolve(process.cwd(), 'src/styles/a11y.css');
const PUBLIC_A11Y_STYLES = resolve(process.cwd(), 'public/css/a11y.css');
const ADMIN_DASHBOARD = resolve(process.cwd(), 'src/components/kychon/AdminDashboardApp.tsx');
const ADMIN_ACCESS_GATE = resolve(process.cwd(), 'src/components/kychon/AdminAccessGate.tsx');
const CONFIG = resolve(process.cwd(), 'src/lib/config.ts');
const I18N = resolve(process.cwd(), 'src/lib/i18n.ts');
const PORTAL = resolve(process.cwd(), 'src/layouts/Portal.astro');
const PAGE_RENDER = resolve(process.cwd(), 'src/lib/page-render.ts');
const SANITIZE_HTML = resolve(process.cwd(), 'src/lib/sanitize-html.ts');
const ADMIN_EDITOR = resolve(process.cwd(), 'src/components/AdminEditor.astro');
const CONTAINER_UTIL = resolve(process.cwd(), 'src/lib/ui/container.ts');
const CSS_COLLISION_REPORT = resolve(process.cwd(), 'scripts/ui-css-collision-report.ts');
const UI_CAPTURE_ROUTES = resolve(process.cwd(), 'scripts/ui-capture-routes.ts');
const SHOWCASE_RENDER = resolve(process.cwd(), 'scripts/_render-showcase.ts');
const TOAST_ISLAND = resolve(process.cwd(), 'src/components/kychon/ToastIsland.tsx');
const SONNER = resolve(process.cwd(), 'src/components/ui/sonner.tsx');
const ctx: BlockRenderContext = { admin: true, locale: 'en', isFeatureEnabled: () => true };

function section(sectionType: string, config: Record<string, unknown>): Section {
  return {
    id: 91,
    page_slug: 'index',
    zone: 'main',
    scope: 'page',
    section_type: sectionType,
    position: 1,
    config,
  };
}

describe('legacy static UI primitives', () => {
  it('renders empty placeholders with token classes instead of ky-text-muted', () => {
    const accordion = renderBlock(section('image_accordion', { panels: [] }), ctx);
    const slideshow = renderBlock(section('slideshow', { items: [] }), ctx);

    expect(accordion).toContain('text-muted-foreground');
    expect(slideshow).toContain('text-muted-foreground');
    expect(accordion).not.toContain('ky-text-muted');
    expect(slideshow).not.toContain('ky-text-muted');
  });

  it('renders the event calendar placeholder without the old skeleton primitive class', () => {
    const html = renderBlock(section('events_calendar', {}), ctx);

    expect(html).toContain('data-events-calendar-skeleton');
    expect(html).toContain('data-events-calendar-controls-host');
    expect(html).toContain('data-events-calendar-viewport');
    expect(html).toContain('data-events-calendar-peek-host');
    expect(html).toContain('animate-pulse');
    expect(html).not.toContain('data-events-calendar-download');
    expect(html).not.toContain('block-events-calendar');
    expect(html).not.toContain('block-events-calendar__skeleton');
    expect(html).not.toContain('event-skeleton-card');
    expect(html).not.toContain(' skeleton');
  });

  it('keeps retired primitive CSS out of source', async () => {
    const blocks = await readFile(BLOCKS, 'utf8');
    const blockHydrators = await readFile(BLOCK_HYDRATORS, 'utf8');
    const embed = await readFile(EMBED, 'utf8');
    const styles = await readFile(STYLES, 'utf8');
    const zoneGridStyles = await readFile(ZONE_GRID_STYLES, 'utf8');
    const eventCalendarRuntime = await readFile(EVENT_CALENDAR_RUNTIME, 'utf8');
    const eventCalendarView = await readFile(EVENT_CALENDAR_VIEW, 'utf8');
    const slideshowRuntime = await readFile(SLIDESHOW_RUNTIME, 'utf8');
    const navDropdown = await readFile(NAV_DROPDOWN, 'utf8');
    const globalStyles = await readFile(GLOBAL_STYLES, 'utf8');
    const adminStyles = await readFile(ADMIN_STYLES, 'utf8');
    const publicZoneGridStyles = await readFile(PUBLIC_ZONE_GRID_STYLES, 'utf8');
    const a11yStyles = await readFile(A11Y_STYLES, 'utf8');
    const publicA11yStyles = await readFile(PUBLIC_A11Y_STYLES, 'utf8');
    const adminDashboard = await readFile(ADMIN_DASHBOARD, 'utf8');
    const adminAccessGate = await readFile(ADMIN_ACCESS_GATE, 'utf8');
    const config = await readFile(CONFIG, 'utf8');
    const i18n = await readFile(I18N, 'utf8');
    const portal = await readFile(PORTAL, 'utf8');
    const pageRender = await readFile(PAGE_RENDER, 'utf8');
    const sanitizeHtml = await readFile(SANITIZE_HTML, 'utf8');
    const adminEditor = await readFile(ADMIN_EDITOR, 'utf8');
    const containerUtil = await readFile(CONTAINER_UTIL, 'utf8');
    const cssCollisionReport = await readFile(CSS_COLLISION_REPORT, 'utf8');
    const uiCaptureRoutes = await readFile(UI_CAPTURE_ROUTES, 'utf8');
    const showcaseRender = await readFile(SHOWCASE_RENDER, 'utf8');
    const toastIsland = await readFile(TOAST_ISLAND, 'utf8');
    const sonner = await readFile(SONNER, 'utf8');

    expect(containerUtil).toContain('mx-auto w-full max-w-[var(--max-width)] px-6');
    expect(containerUtil).not.toContain('ky-container');
    expect(blocks).toContain('constrainedContainerHtml');
    expect(blocks).toContain('data-layout-container');
    expect(blocks).toContain('Runtime receives the concrete `[data-block-hydrate]` host');
    expect(blocks).toContain("getAttribute('data-block-hydrate') !== 'polls'");
    expect(blocks).toContain("getAttribute('data-block-hydrate') !== 'event_countdown'");
    expect(blocks).toContain("getAttribute('data-block-hydrate') !== 'events_list'");
    expect(blocks).toContain("getAttribute('data-block-hydrate') !== 'events_calendar'");
    expect(blocks).toContain("getAttribute('data-block-hydrate') !== 'slideshow'");
    expect(blocks).not.toContain('el.querySelector(\'[data-block-hydrate="polls"]\')');
    expect(blocks).not.toContain('el.querySelector(\'[data-block-hydrate="event_countdown"]\')');
    expect(blocks).not.toContain('el.querySelector(\'[data-block-hydrate="slideshow"]\')');
    expect(blockHydrators).toContain('function isHydrateHost');
    expect(blockHydrators).toContain('function hydrationShell');
    expect(blockHydrators).not.toContain('querySelector');
    expect(blockHydrators).not.toContain('.closest(');
    expect(blocks).toContain('sectionShellFor');
    expect(blocks).not.toContain(".closest('[data-section]')");
    expect(blocks).toContain('data-year="auto"');
    expect(blocks).toContain('new Date().getFullYear()');
    expect(blocks).not.toContain('class="ky-container"');
    expect(blocks).not.toContain('ky-container');
    expect(blocks).not.toContain('ky-text-muted');
    expect(blocks).not.toMatch(/class="[^"]*\bsection\b/);
    expect(blocks).not.toContain('section-events-calendar');
    expect(blocks).not.toContain('section-activity');
    expect(blocks).toContain('data-footer-block');
    expect(blocks).toContain('data-footer-links');
    expect(blocks).not.toMatch(/class="[^"]*\bfooter(?:-|\b)/);
    expect(embed).not.toMatch(/class="[^"]*\bsection\b/);
    expect(blocks).not.toContain('event-skeleton-card');
    expect(blocks).not.toContain('block-events-calendar__skeleton');
    expect(blocks).not.toContain(' skeleton"></div>');
    expect(embed).not.toContain('block-embed');
    expect(styles).toContain('[data-section]');
    expect(styles).not.toMatch(/\.section(?:[.{:#\s-]|$)/);
    expect(styles).toContain('[data-footer-shell]');
    expect(styles).toContain('[data-footer-links]');
    expect(styles).not.toMatch(/\.footer(?:[.{:#\s-]|$)/);
    expect(styles).not.toMatch(/\.ky-text-muted\b/);
    expect(styles).not.toMatch(/\.skeleton(?:[.{:#\s-]|$)/);
    expect(styles).not.toContain('skeleton-pulse');
    expect(styles).not.toContain('block-events-calendar__skeleton');
    expect(styles).not.toContain('section-shape-divider');
    expect(styles).not.toContain('shape-divider__');
    expect(styles).not.toContain('admin-account-security');
    expect(styles).not.toContain('admin-checklist');
    expect(styles).not.toContain('.section-visible');
    expect(styles).not.toMatch(/\.toast(?:[.{:#\s-]|$)/);
    expect(styles).not.toContain('.toast-container');
    expect(styles).not.toContain('toast-success');
    expect(styles).not.toMatch(/\.auth-(?:modal|panel|divider)\b/);
    expect(styles).not.toMatch(/\.table-wrap\b/);
    expect(styles).not.toMatch(/\.sr-only\b/);
    expect(styles).not.toMatch(/\.page(?:[.{:#\s-]|$)/);
    expect(styles).not.toMatch(/\.page-content\b/);
    expect(styles).not.toContain('#page-content');
    // Section reveal animation removed entirely: neither the JS-driven
    // data-section-visible mechanism nor a CSS @keyframes section-fade-in
    // exists; the first paint just shows sections without an opacity ramp.
    expect(styles).not.toContain('@keyframes section-fade-in');
    expect(styles).not.toContain('data-section-visible');
    expect(styles).toContain('[data-nav-shell] [data-layout-container]');
    expect(styles).not.toContain('.nav [data-layout-container]');
    expect(styles).toContain('[data-nav-links]:not([data-nav-source-mobile="true"])');
    expect(styles).toContain('overscroll-behavior-inline: contain');
    expect(styles).not.toContain('ky-container');
    expect(zoneGridStyles).toContain('[data-layout-container]');
    expect(zoneGridStyles).not.toContain('ky-container');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__controls');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__seg-btn');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__filter-chip');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__peek');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__empty');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__chip');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__avatar');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__badge');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__more');
    expect(eventCalendarRuntime).not.toContain('block-events-calendar__');
    expect(eventCalendarRuntime).not.toContain('document.createElement');
    expect(eventCalendarRuntime).not.toContain('innerHTML');
    expect(eventCalendarRuntime).not.toContain('insertAdjacentHTML');
    expect(eventCalendarRuntime).not.toContain('appendChild');
    expect(eventCalendarRuntime).not.toContain('downloadIcs');
    expect(eventCalendarRuntime).not.toContain('data-events-calendar-download');
    expect(eventCalendarRuntime).not.toContain('eventsCalendarNavBound');
    expect(eventCalendarRuntime).not.toContain('eventsCalendarViewBound');
    expect(eventCalendarRuntime).not.toContain('eventsCalendarFilterBound');
    expect(eventCalendarRuntime).not.toContain('eventsCalendarPeekBound');
    expect(eventCalendarRuntime).not.toContain('eventsCalendarIcsBound');
    expect(eventCalendarRuntime).not.toContain('eventsCalendarPeekButtonBound');
    expect(eventCalendarRuntime).not.toContain('eventsCalendarCellBound');
    expect(eventCalendarRuntime).not.toContain('eventsCalendarHoverBound');
    expect(eventCalendarRuntime).not.toContain('bindCells');
    expect(eventCalendarRuntime).not.toContain('button[data-nav]');
    expect(eventCalendarRuntime).not.toContain('button[data-view]');
    expect(eventCalendarRuntime).not.toContain('button[data-filter]');
    expect(eventCalendarRuntime).not.toContain('querySelector');
    expect(eventCalendarRuntime).not.toContain("querySelectorAll<HTMLElement>('[data-day-peek]')");
    expect(eventCalendarRuntime).not.toContain("querySelectorAll<HTMLElement>('[data-events-calendar-cell]')");
    expect(eventCalendarRuntime).not.toContain('.closest(');
    expect(eventCalendarRuntime).not.toContain('[data-events-calendar-cell][data-day=');
    expect(eventCalendarRuntime).toContain('findDirectElementChild');
    expect(eventCalendarRuntime).toContain('nearestAncestorWithAttribute');
    expect(eventCalendarRuntime).not.toContain('function findDirectChildWithAttribute');
    expect(eventCalendarRuntime).toContain('sortableIdFor');
    expect(eventCalendarRuntime).toContain('createRoot');
    expect(eventCalendarRuntime).toContain('EventsCalendarControls');
    expect(eventCalendarView).toContain('@/components/kychon/ui');
    expect(eventCalendarView).toContain('onNavigate');
    expect(eventCalendarView).not.toContain('onAddToCalendar');
    expect(eventCalendarView).toContain('onDayPeek');
    expect(eventCalendarView).toContain('onCellClick');
    expect(eventCalendarView).toContain('focusDay');
    expect(eventCalendarView).toContain('cellRefs');
    expect(eventCalendarView).toContain('asChild');
    expect(eventCalendarView).toContain('data-events-calendar-controls-host');
    expect(eventCalendarView).toContain('data-events-calendar-peek-host');
    expect(eventCalendarView).not.toContain('block-events-calendar__');
    expect(slideshowRuntime).not.toContain('IntersectionObserver');
    expect(slideshowRuntime).not.toContain('querySelector');
    expect(slideshowRuntime).not.toContain('data-slide-next');
    expect(slideshowRuntime).not.toContain('data-slide-prev');
    expect(slideshowRuntime).not.toContain('data-slideshow-slide');
    expect(slideshowRuntime).not.toContain('data-slideshow-dot');
    expect(slideshowRuntime).not.toContain('data-slideshow-live');
    expect(slideshowRuntime).toContain('SlideshowCarousel');
    expect(slideshowRuntime).toContain('initSlideshows');
    expect(slideshowRuntime).toContain('collectDescendantElements');
    expect(navDropdown).toContain('NavBlockContent');
    expect(navDropdown).toContain('createRoot');
    expect(navDropdown).not.toContain('chevronBound');
    expect(navDropdown).not.toContain('navKeyboardBound');
    expect(navDropdown).not.toContain('navHoverBound');
    expect(navDropdown).not.toContain('navToggleBound');
    expect(navDropdown).not.toContain('querySelector');
    expect(navDropdown).not.toContain('querySelectorAll');
    expect(navDropdown).not.toContain('.closest(');
    expect(navDropdown).not.toContain('.matches(');
    expect(navDropdown).not.toContain('[data-nav-trigger]');
    expect(navDropdown).not.toContain('[data-nav-menu]:not([hidden])');
    expect(globalStyles).not.toContain('block-events-calendar.css');
    expect(globalStyles).not.toContain('nav-dropdown.css');
    expect(adminStyles).not.toContain('block-embed');
    expect(adminStyles).not.toContain('.admin-drop-indicator');
    expect(adminStyles).not.toContain('admin-nav-edit-btn');
    expect(adminStyles).not.toContain('admin-toast');
    expect(adminStyles).not.toContain('admin-section-actions');
    expect(adminStyles).not.toContain('admin-save-success');
    expect(adminStyles).not.toContain('admin-save-error');
    expect(adminStyles).not.toContain('admin-save-pulse');
    expect(adminStyles).not.toContain('.tiptap-active');
    expect(adminStyles).not.toContain('.uploading');
    expect(adminStyles).not.toContain('.dragging');
    expect(adminStyles).not.toContain('.admin ');
    expect(adminStyles).not.toMatch(/\.admin\b/);
    expect(adminStyles).not.toContain('body.admin');
    expect(adminStyles).not.toContain('body.admin-dragging');
    expect(adminStyles).toContain('[data-layout-container]:empty::before');
    expect(adminStyles).not.toContain('ky-container');
    expect(publicZoneGridStyles).toContain('[data-layout-container]');
    expect(publicZoneGridStyles).toContain('#sections > [data-react-html-children] > [data-column-span="1"]');
    expect(publicZoneGridStyles).toContain(
      '[data-zone="footer"] > [data-layout-container] > [data-react-html-children] > [data-column-span="1"]',
    );
    expect(publicZoneGridStyles).not.toContain('ky-container');
    for (const stylesheet of [a11yStyles, publicA11yStyles]) {
      expect(stylesheet).toContain('html[data-high-contrast="true"]');
      expect(stylesheet).toContain('html[data-reduced-motion="true"]');
      expect(stylesheet).not.toContain('.wl-skip-nav');
      expect(stylesheet).not.toContain('.wl-high-contrast');
      expect(stylesheet).not.toContain('.wl-reduced-motion');
      expect(stylesheet).not.toContain('.wl-sr-live');
      expect(stylesheet).not.toContain('wl-a11y');
      expect(stylesheet).not.toContain('.wl-toggle');
    }
    expect(adminDashboard).toContain('@/components/kychon/ui');
    expect(adminDashboard).not.toContain('admin-account-security');
    expect(adminDashboard).not.toContain('admin-checklist');
    expect(portal).toContain('class="flex min-h-screen flex-col"');
    expect(portal).toContain('class="flex-1 py-8" id="main-content"');
    expect(portal).toContain('constrainedContainerClass');
    expect(portal).toContain('data-layout-container');
    expect(portal).toContain('data-footer-shell');
    expect(portal).not.toContain('ky-container');
    expect(portal).not.toContain('class="footer"');
    expect(portal).not.toContain('class="page"');
    expect(portal).not.toContain('class="page-content"');
    expect(portal).not.toContain('MutationObserver');
    expect(portal).not.toContain('IntersectionObserver');
    expect(portal).not.toContain('data-section-visible');
    expect(portal).not.toContain("document.querySelectorAll('main [data-section]')");
    expect(portal).not.toContain('setYear');
    expect(portal).not.toContain('data-year="auto"');
    expect(portal).not.toContain("document.querySelectorAll('[data-section]')");
    expect(portal).not.toContain("document.querySelectorAll('.section')");
    expect(portal).not.toContain("classList?.contains('section')");
    expect(portal).not.toContain("classList.add('section-visible')");
    expect(portal).not.toContain('.section-visible');
    expect(portal).not.toContain('wl-skip-nav');
    expect(portal).not.toContain('wl-sr-live" class="wl-sr-live');
    expect(portal).toContain('id="wl-sr-live" class="sr-only"');
    expect(portal).toContain('id="wl-theme-vars"');
    expect(config).toContain('document.documentElement.dataset.highContrast');
    expect(config).toContain('document.documentElement.dataset.reducedMotion');
    expect(config).not.toContain("classList.add('wl-high-contrast')");
    expect(config).not.toContain("classList.add('wl-reduced-motion')");
    expect(config).not.toContain('document.createElement');
    expect(config).not.toContain('appendChild');
    expect(config).not.toContain('getElementById');
    expect(config).not.toContain('querySelector');
    expect(config).toContain('findDirectElementChild');
    expect(config).not.toContain('function findHeadChild');
    expect(i18n).not.toContain('getElementById');
    expect(i18n).not.toContain('querySelector');
    expect(i18n).toContain('findDescendantElementById');
    expect(pageRender).toContain('findDirectElementChild');
    expect(pageRender).toContain("child.hasAttribute('data-layout-container')");
    expect(pageRender).toContain("child.id === 'sections'");
    expect(pageRender).toContain('hydrateHosts()');
    expect(pageRender).not.toContain('querySelector');
    expect(pageRender).not.toContain('getElementById');
    expect(pageRender).not.toContain('.closest(');
    expect(pageRender).toContain('nearestElementWithAttribute');
    expect(pageRender).toContain('await type.hydrate(host, section, ctx)');
    expect(pageRender).not.toContain("root?.querySelector('[data-block-hydrate]')");
    expect(pageRender).not.toContain('matching?.parentElement');
    expect(pageRender).not.toContain("querySelectorAll('[data-sortable-id]')");
    expect(pageRender).not.toContain("querySelectorAll('[data-block-hydrate]')");
    expect(pageRender).not.toContain("querySelectorAll<HTMLElement>('[data-block-hydrate]')");
    expect(pageRender).not.toContain('rendered: HTMLElement[]');
    expect(pageRender).toContain("import { renderReactHtmlChildren } from './react-html-children'");
    expect(pageRender).toContain('renderReactHtmlChildren(sectionsHost, newHtml)');
    expect(pageRender).not.toContain("from './dom-fragment'");
    expect(pageRender).not.toContain('new DOMParser()');
    expect(pageRender).not.toContain('replaceChildren');
    expect(pageRender).not.toContain('ky-container');
    expect(adminEditor).toContain("child.hasAttribute('data-layout-container')");
    expect(adminEditor).toContain("child.id === 'sections'");
    expect(adminEditor).toContain('../lib/react-html-children');
    expect(adminEditor).toContain('function renderedChildrenHost');
    expect(adminEditor).toContain('REACT_HTML_CHILDREN_ATTR');
    expect(adminEditor).not.toContain(':scope > [data-layout-container]');
    expect(adminEditor).not.toContain("querySelector('#sections')");
    expect(adminEditor).toContain("import('sortablejs')");
    expect(adminEditor).toContain('Sortable.create');
    expect(adminEditor).not.toContain('../lib/dom-fragment');
    expect(adminEditor).not.toContain('moveNodeBefore');
    expect(adminEditor).not.toContain('moveNodeAfter');
    expect(adminEditor).not.toContain('removeNode');
    expect(adminEditor).not.toContain('replaceNodeWith');
    expect(adminEditor).toContain('findDescendantElementById');
    expect(adminEditor).toContain('showAdminInlineTextPrompt');
    expect(adminEditor).not.toContain('contentEditable');
    expect(adminEditor).not.toContain('MutationObserver');
    expect(adminEditor).not.toContain('document.createRange');
    expect(adminEditor).not.toContain('selectNodeContents');
    expect(adminEditor).not.toContain('new DOMParser()');
    expect(adminEditor).not.toContain('replaceChildren');
    expect(adminEditor).not.toContain('.closest(');
    expect(adminEditor).not.toContain('getElementById');
    expect(adminEditor).not.toContain('.before(');
    expect(adminEditor).not.toContain('.after(');
    expect(adminEditor).not.toContain('.replaceWith(');
    expect(adminEditor).not.toContain('.remove(');
    expect(adminEditor).not.toContain('ky-container');
    expect(adminAccessGate).toContain('AdminAccessShellView');
    expect(adminAccessGate).toContain('AuthGate');
    expect(adminAccessGate).not.toContain('querySelector');
    expect(adminAccessGate).not.toContain('data-admin-content');
    expect(sanitizeHtml).toContain("from 'ultrahtml'");
    expect(sanitizeHtml).toContain('function sanitizeRichHtmlAst');
    expect(sanitizeHtml).toContain('sanitizeChildren');
    expect(sanitizeHtml).not.toContain("from './dom-fragment'");
    expect(sanitizeHtml).not.toContain('parseHtmlBody');
    expect(sanitizeHtml).not.toContain('serializeHtmlChildren');
    expect(sanitizeHtml).not.toContain('snapshotChildNodes');
    expect(sanitizeHtml).not.toContain('removeNode');
    expect(sanitizeHtml).not.toContain('unwrapElement');
    expect(sanitizeHtml).not.toContain('DOMParser');
    expect(sanitizeHtml).not.toContain('childNodes');
    expect(sanitizeHtml).not.toContain('innerHTML');
    expect(sanitizeHtml).not.toContain('insertAdjacentHTML');
    expect(sanitizeHtml).not.toContain('insertBefore');
    expect(sanitizeHtml).not.toContain('removeChild');
    expect(sanitizeHtml).not.toContain('.remove(');
    expect(cssCollisionReport).toContain('data-layout-container');
    expect(cssCollisionReport).toContain('Retired as a Kychon public component class');
    expect(cssCollisionReport).not.toContain('ky-container');
    expect(cssCollisionReport).not.toContain('ky-text-muted');
    expect(cssCollisionReport).not.toContain('retained temporarily');
    expect(uiCaptureRoutes).toContain('[data-events-page] [data-event-card]');
    expect(uiCaptureRoutes).toContain('[data-resources-page] [data-resource-card]');
    expect(uiCaptureRoutes).toContain('[data-forum-page] [data-forum-category-card]');
    expect(uiCaptureRoutes).toContain("getByRole('heading', { name: 'Site Settings', level: 2 })");
    expect(uiCaptureRoutes).toContain("getByRole('heading', { name: route.expectedTitle, level: 1 })");
    expect(uiCaptureRoutes).not.toContain('waitForFunction');
    expect(uiCaptureRoutes).not.toContain('data-admin-content');
    expect(uiCaptureRoutes.indexOf("context.route('**/functions/v1/**'")).toBeLessThan(
      uiCaptureRoutes.indexOf("context.route('**/functions/v1/kychon-api'"),
    );
    expect(uiCaptureRoutes).toContain("operation === 'auth.whoami'");
    expect(uiCaptureRoutes).not.toContain('document.querySelector');
    expect(uiCaptureRoutes).not.toContain('document.querySelectorAll');
    expect(uiCaptureRoutes).not.toContain('#events-list .card');
    expect(uiCaptureRoutes).not.toContain('#resources-grid .card');
    expect(uiCaptureRoutes).not.toContain('.forum-category');
    expect(showcaseRender).toContain('data-layout-container');
    expect(showcaseRender).toContain('data-nav-shell');
    expect(showcaseRender).not.toContain('class="nav"');
    expect(showcaseRender).not.toContain('.preview-label');
    expect(showcaseRender).not.toContain('data-section-visible');
    expect(showcaseRender).toContain('inlineModuleExports');
    expect(showcaseRender).toContain('initSlideshows();');
    expect(showcaseRender).not.toContain('document.querySelectorAll');
    expect(showcaseRender).not.toContain("document.querySelectorAll('main [data-section]')");
    expect(showcaseRender).not.toContain("document.querySelectorAll('[data-section]')");
    expect(showcaseRender).not.toContain('ky-container');
    expect(showcaseRender).not.toContain('page-content');
    expect(showcaseRender).not.toContain('.section-visible');
    expect(showcaseRender).not.toContain("classList.add('section-visible')");
    expect(toastIsland).toContain('Toaster');
    expect(toastIsland).toContain('toast.success');
    expect(sonner).toContain('sonner');
    expect(sonner).toContain('border-border bg-background text-foreground shadow-lg');
    expect(sonner).toContain('text-muted-foreground');
    expect(sonner).not.toContain('ky-toast');
    expect(sonner).not.toContain('group-[');
    expect(sonner).not.toContain('className="toaster');
  });
});
